# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binaryinstall < Formula
  desc "Install GitHub release binaries onto a server via SCP."
  homepage "https://github.com/dropsite-ai/binaryinstall"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.5.0/binaryinstall_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "45fb00119c9d602ad0c1b3da0fe82532ebd50ffccc1c2a17088c7b3990601240"

      def install
        bin.install "binaryinstall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.5.0/binaryinstall_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "ef7904c4e7571b297ed1a034b898aaea354e2a2ddf94adec8c64b63f124117c9"

      def install
        bin.install "binaryinstall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.5.0/binaryinstall_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "48e55000cc1500c393efa97d8475f40fb2b1e19588581b5efc1cf3afaeb1cdd1"

        def install
          bin.install "binaryinstall"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.5.0/binaryinstall_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "543b9c30c76d8f7b31d4a1f1952e1d86ac8bf7c0fff94415f8fd995a3ff0bc5e"

        def install
          bin.install "binaryinstall"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
