# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binaryinstall < Formula
  desc "Install GitHub release binaries onto a server via SCP."
  homepage "https://github.com/dropsite-ai/binaryinstall"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.4.0/binaryinstall_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "4db9a750207baf42b359410954c2b44566b7a932b25f9c71dff6cfe7459eb480"

      def install
        bin.install "binaryinstall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.4.0/binaryinstall_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "9c26144ae4c939467f4b19825d9050ddfae8b5d283a0cea896c764d4b037c9c9"

      def install
        bin.install "binaryinstall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.4.0/binaryinstall_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "d2589eff59356087054fa8cac9514baa06bf56973efc026b2b38407b600353f1"

        def install
          bin.install "binaryinstall"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.4.0/binaryinstall_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "713139892332f67ae8cb223b627b081075ad77759f11ae74b91a75b4a0e33cc5"

        def install
          bin.install "binaryinstall"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
