# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binaryinstall < Formula
  desc "Install GitHub release binaries onto a server via SCP."
  homepage "https://github.com/dropsite-ai/binaryinstall"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.3.0/binaryinstall_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "bd1940654057ea4e15f0ac30d15269c37f37764b538a42675e58b2a6d3c3d436"

      def install
        bin.install "binaryinstall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.3.0/binaryinstall_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "2ec778a6a7ccdde00ed208085d2ae694fa5d33afa6aa7bada916ea91559b1b0e"

      def install
        bin.install "binaryinstall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.3.0/binaryinstall_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "2bc382791c6d7b3f2f916a38947c01ec4d8d2615d338f4b40b4048bf16404086"

        def install
          bin.install "binaryinstall"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/binaryinstall/releases/download/0.3.0/binaryinstall_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "b2bfeb5b4687ff91d32894b1bf3f62001757c38130252f518787af8561959024"

        def install
          bin.install "binaryinstall"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
