# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Config < Formula
  desc "YAML configuration utility functions and CLI."
  homepage "https://github.com/dropsite-ai/config"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/config/releases/download/2.0.0/config_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "cfed4fb4cf2cb5c05bb44fab188272a3c4e6680157b038d96fa818e34e214363"

      def install
        bin.install "config"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/config/releases/download/2.0.0/config_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "23fc019979aefe07339df00b8355388f2705ad00797d47cf020166a888941b37"

      def install
        bin.install "config"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/config/releases/download/2.0.0/config_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "9db338929ffc44a9f84a6ffb26e18e69fe27bdf0f819a37ca5b33d474040c483"

        def install
          bin.install "config"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/config/releases/download/2.0.0/config_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "c10d1861b3bbd1dd35fee3fd7b9458ee8cafa31b7ef9bfd6edaaf8b08b10ea83"

        def install
          bin.install "config"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
