# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Config < Formula
  desc "YAML configuration utility functions and CLI."
  homepage "https://github.com/dropsite-ai/config"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/config/releases/download/0.4.0/config_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "d1722fb620de89f251d3ba2001e3499ed338a1e1bdf51d2f248f56d9d6396192"

      def install
        bin.install "config"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/config/releases/download/0.4.0/config_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "b5592799afdeab4df494bca0ecf9c59d72abe602b1b326879d6198d97c55a7e9"

      def install
        bin.install "config"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/config/releases/download/0.4.0/config_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "5fccaa4e2c7290b14ca04357b85e1a84ff76b1d3d889cf79a6a30dc3b87139a2"

        def install
          bin.install "config"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/config/releases/download/0.4.0/config_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "4add282c14aee09a7b2fc6d7ddb6246982648580a28456a5527501f7cda8c4ca"

        def install
          bin.install "config"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
