# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Config < Formula
  desc "YAML configuration utility functions and CLI."
  homepage "https://github.com/dropsite-ai/config"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/config/releases/download/1.1.0/config_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "e44149546227101b20f21dc20a4cd48d8d9b4cabe672566ab8a5b0dd6be25ad1"

      def install
        bin.install "config"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/config/releases/download/1.1.0/config_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "3673cf700ff265d0957863708dc97435ac7a8b08e8fa1b86b98efa5d0fd6fe64"

      def install
        bin.install "config"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/config/releases/download/1.1.0/config_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "f03bfcab5cccd809da6e820cd2d667a0316b4b98a4c3c9f4e1415d7181250bca"

        def install
          bin.install "config"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/config/releases/download/1.1.0/config_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "92d2ac4c4d6a0d78cdcf9116bfdccc12dad25dcad39f7e29a0196a1d15c54d5c"

        def install
          bin.install "config"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
