# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deploy < Formula
  desc "Install GitHub release binaries onto a server via SCP."
  homepage "https://github.com/dropsite-ai/deploy"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/deploy/releases/download/0.7.0/deploy_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "9061014573ba46049f547a0fc4f7d2ef74a33ef2ce3478259addcbe52a570d66"

      def install
        bin.install "deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/deploy/releases/download/0.7.0/deploy_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "0a9ce222317108ac99fb937821dd0719c5c5f08ff93cea03b0661a1d6331688f"

      def install
        bin.install "deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/deploy/releases/download/0.7.0/deploy_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "734e86e5f394b7502ad8ef231e500c0017532d77cbd976322f7ef6be2225737d"

        def install
          bin.install "deploy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/deploy/releases/download/0.7.0/deploy_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "1cae37cada027d4c990a37427d5dab71d0578b0eef01eef6a6c8ad32ea110cad"

        def install
          bin.install "deploy"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
