# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deploy < Formula
  desc "Install GitHub release binaries onto a server via SCP."
  homepage "https://github.com/dropsite-ai/deploy"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/deploy/releases/download/0.6.0/deploy_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "c3e311123d48f277d31797020638108abe02b73c009e222134b908279ebb7497"

      def install
        bin.install "deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/deploy/releases/download/0.6.0/deploy_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "8926b828787713f59c340d17e221ac6f93e72f8ae6714725dc9556bb8a6b20e3"

      def install
        bin.install "deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/deploy/releases/download/0.6.0/deploy_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "fea54181bc7dc64faecb899cbfb21ee0aac25e89e4c8cd1fdc669ac3b3c7bc4b"

        def install
          bin.install "deploy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/deploy/releases/download/0.6.0/deploy_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "c6df71a27112a09ca36d8f5837175b0a19a7f265afba185f6ef8584bfaf1a0a4"

        def install
          bin.install "deploy"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
