# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deploy < Formula
  desc "Install GitHub release binaries onto a server via SCP."
  homepage "https://github.com/dropsite-ai/deploy"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/deploy/releases/download/0.4.0/deploy_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "77c39ce779b836a9e2c2d61ca491e9738a8ebd0beb5a8dcd8a0e1455891edf0f"

      def install
        bin.install "deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/deploy/releases/download/0.4.0/deploy_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "ad38006018ca1982793c210a3c03cadf01b9c008d925be813c59253fcee4bc2c"

      def install
        bin.install "deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/deploy/releases/download/0.4.0/deploy_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "d4afadbb3433833c9701e97a9847e4d3374359d05d6eb1956d7bc40f2c902d4c"

        def install
          bin.install "deploy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/deploy/releases/download/0.4.0/deploy_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "2dafb1779f1fcde4aede96bf5cd410aad626ca60b9155439a6e0bc07537d67a8"

        def install
          bin.install "deploy"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
