# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fileutils < Formula
  desc "fileutils for dropsite-ai."
  homepage "https://github.com/dropsite-ai/fileutils"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/fileutils/releases/download/0.1.0/fileutils_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "92bf46919155f612bb089409f74318de2642baea05bef094cb2db8d98c6764cd"

      def install
        bin.install "fileutils"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/fileutils/releases/download/0.1.0/fileutils_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "8132359a088756e0b0c0819c25299c2dac2adf7608918621c0e78076450605e4"

      def install
        bin.install "fileutils"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/fileutils/releases/download/0.1.0/fileutils_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "ec40c272d42130141c8cd89bd31b0aa80f45a5826d2d7684dc3a3d87c3f92edc"

        def install
          bin.install "fileutils"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/fileutils/releases/download/0.1.0/fileutils_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "499b75386fa2ac6444c3fec7bb6cdacf25df3cb245dde1a83c9d877be03e30c2"

        def install
          bin.install "fileutils"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
