# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghdownloader < Formula
  desc "Download latest releases from a GitHub repository."
  homepage "https://github.com/dropsite-ai/ghdownloader"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.1.0/ghdownloader_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "62c1ce59f63e2fc84299575729f63c24897230847b5a4a333da90997ed98d17e"

      def install
        bin.install "ghdownloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.1.0/ghdownloader_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "ead97f967ac679fde8ccb430a78a05380d6e05a333ba243f41cf5897b5e1c388"

      def install
        bin.install "ghdownloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.1.0/ghdownloader_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "9da59e7ccb622f332e0bd9ff4617b80bc0b367b1908e17e432094586a6f67d2d"

        def install
          bin.install "ghdownloader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.1.0/ghdownloader_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "43c84bd2cf97187b899df2a8b69d6e5492829180fe9b63c43c4b0cbaaa788cab"

        def install
          bin.install "ghdownloader"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
