# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghdownloader < Formula
  desc "Download latest releases from a GitHub repository."
  homepage "https://github.com/dropsite-ai/ghdownloader"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.2.0/ghdownloader_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "195de680d4c0bced9f47de71d7cb7ca0fdd8382d31c12b10008d93993992d8d4"

      def install
        bin.install "ghdownloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.2.0/ghdownloader_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "b9dc95e8e7f39a746a5de7e78ee6ee04f8b73c79e0a7467eb21cc593558e0265"

      def install
        bin.install "ghdownloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.2.0/ghdownloader_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "f082f29b88ccd189a0523f7afdd3e0ef7b71d341ce53c0ed849e0492dde508b7"

        def install
          bin.install "ghdownloader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/ghdownloader/releases/download/1.2.0/ghdownloader_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "cffb533998f8ae5bf0ea96ac0a0b22db51bf1f6d018b275352b0d886e29d0b3e"

        def install
          bin.install "ghdownloader"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
