# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghinstaller < Formula
  desc "Install GitHub release binaries onto a server via SCP."
  homepage "https://github.com/dropsite-ai/ghinstaller"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/ghinstaller/releases/download/1.0.0/ghinstaller_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "48e126e610e7fda2df08112500a04905c809cd716184a8f29cbd526ea432a152"

      def install
        bin.install "ghinstaller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/ghinstaller/releases/download/1.0.0/ghinstaller_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "b7a7c3d905c91be22b367b02c303404c9d50d5176e6af5b2996cad0a96eb8c46"

      def install
        bin.install "ghinstaller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/ghinstaller/releases/download/1.0.0/ghinstaller_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "8359ae31d61ef5d791cda66e93322cf9172cb909ffae5d6547d72136ba2f386a"

        def install
          bin.install "ghinstaller"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/ghinstaller/releases/download/1.0.0/ghinstaller_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "767cbf13bd851c801f09434d70249960cba242291030d2b987e72165b0441502"

        def install
          bin.install "ghinstaller"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
