# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotemplate < Formula
  desc "gotemplate for dropsite-ai."
  homepage "https://github.com/dropsite-ai/gotemplate"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/gotemplate/releases/download/1.0.0/gotemplate_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "8ae6c9f4c01f5b34a57472e7e61bb2c0155015e3d0b950da65fbac4d3250b506"

      def install
        bin.install "gotemplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/gotemplate/releases/download/1.0.0/gotemplate_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "f76d073baf156e5c533e843296c128aad5352edb3cffd16130edeadd4c2370b5"

      def install
        bin.install "gotemplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/gotemplate/releases/download/1.0.0/gotemplate_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "4229c6a40a6b88d00d6988553ee902cfc57734d2f272d64224320059e93cbcaa"

        def install
          bin.install "gotemplate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/gotemplate/releases/download/1.0.0/gotemplate_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "be6df47fa16694fcf6f092db151dda736b1915838c5d7d250eabf76eda60a1c7"

        def install
          bin.install "gotemplate"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
