# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotemplate < Formula
  desc "gotemplate for dropsite-ai."
  homepage "https://github.com/dropsite-ai/gotemplate"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/gotemplate/releases/download/1.1.1/gotemplate_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "071253e3a93a57f61f2411faff1ade5d28c3fa46bbdd2d70030e9463bffce02b"

      def install
        bin.install "gotemplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/gotemplate/releases/download/1.1.1/gotemplate_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "a6383bc120369ff76d3f2fe03e78446ff42b60a326ef706b6ebad59759b3a8d9"

      def install
        bin.install "gotemplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/gotemplate/releases/download/1.1.1/gotemplate_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "ea9c2e95a0494c9111f5187243c94eb02df423d73ebac3aa4b9b960796bb7b8a"

        def install
          bin.install "gotemplate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/gotemplate/releases/download/1.1.1/gotemplate_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "642553792d5205686c1f04f6039430b08538430bcee5110d976d4e33341a00dd"

        def install
          bin.install "gotemplate"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
