# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llmfs < Formula
  desc "Virtual Filesystem Server for LLMs and Humans."
  homepage "https://github.com/dropsite-ai/llmfs"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/llmfs/releases/download/1.4.0/llmfs_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "c388818afd5592f836d7a9a8f4f8d79ec31b8ca9e4870237f7393c89ce850be1"

      def install
        bin.install "llmfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/llmfs/releases/download/1.4.0/llmfs_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "7453c21b487c8a6ab7103207d22f0ed45d7c9556783c871e6710846ddfb14d96"

      def install
        bin.install "llmfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/llmfs/releases/download/1.4.0/llmfs_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "23fef4f345142113a5a5d437a677f6db9b9fc4bb53b1d9a2165ab0a3e2db7da5"

        def install
          bin.install "llmfs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/llmfs/releases/download/1.4.0/llmfs_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "c132142d9789f642b4c3b16548d5f150031cb51762be4588994d0669168bbdac"

        def install
          bin.install "llmfs"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
