# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llmfs < Formula
  desc "Virtual Filesystem Server for LLMs and Humans."
  homepage "https://github.com/dropsite-ai/llmfs"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/llmfs/releases/download/1.0.2/llmfs_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "463ac32e9d910d7987b3d9e88cf3cb0e9d45f0bbb9433c536aa9020e7f183e4d"

      def install
        bin.install "llmfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/llmfs/releases/download/1.0.2/llmfs_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "b3720a1dffd8862458c221e1a27959a881bb27371ee2e5eedeadb218df72840c"

      def install
        bin.install "llmfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/llmfs/releases/download/1.0.2/llmfs_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "9cc006c09ec58057edaf6a31125aafa6aaa0d7d780b10eb1831a0165e3df8711"

        def install
          bin.install "llmfs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/llmfs/releases/download/1.0.2/llmfs_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "aaeb5174342535e8304237a91e605bc8ff53e5f357030cf4c550894de405309b"

        def install
          bin.install "llmfs"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
