# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamledit < Formula
  desc "Lightweight Go package and CLI tool for reading and updating YAML files using dot-notation"
  homepage "https://github.com/dropsite-ai/yamledit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropsite-ai/yamledit/releases/download/0.2.0/yamledit_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "12c340e3a560aa8572dbd2ea7802e37370aabc1d028d8b1a0a1ce0124500b62a"

      def install
        bin.install "yamledit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropsite-ai/yamledit/releases/download/0.2.0/yamledit_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "ca396cbcb302de7ccea501fa4226ab9121fb5a26b0f17925cdf3b8ca1a055caf"

      def install
        bin.install "yamledit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/yamledit/releases/download/0.2.0/yamledit_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "6969fdf02b550ff9ebc393465c1d3c88e21a4dab0771e354a4280693a22347ea"

        def install
          bin.install "yamledit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dropsite-ai/yamledit/releases/download/0.2.0/yamledit_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream"
          ]
        sha256 "c24f0736172618b39a2309bedd70d7d1088c32997e7e48db0a5a3e5f1f2b8f89"

        def install
          bin.install "yamledit"
        end
      end
    end
  end

  def caveats
    <<~EOS
      For usage instructions, please refer to the project's README.
    EOS
  end
end
